### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by QuadeHale** [sarfata/pi-blaster.js#13]
With Node 7.0.0, you get the following:
`(node:902) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`
I've tried supplying a callback as a third parameter, but alas it's not working.

**Comment by mylawacad** [comment]
Same happens on node 8.1.1
Please let me know if you found a fix

**Comment by SephReed** [comment]
I was getting this too.

The solution:  give a dummy function to `fs.close`

    var  dummyFn = function(){};
    //......snip.........
    } else {
	 fs.close(fd, dummyFn);
	 if (callback && typeof callback == 'function') {callback()};
    }


To solve a problem like this yourself in the future, try `sudo node --trace-deprecation my_app.js`

**Comment by cisasteelersfan** [comment]
Likewise.

I changed the line to:
`fs.close(fd, function(){});`
