### ISSUE TITLE
Controlling the Pi-Blaster.js from a web page

### ISSUE THREAD

**Issue by TinkerShadow** [sarfata/pi-blaster.js#14]
I am working towards controlling a set of RGB Led strips... As the Pi will be worked away somewhere I wonder if you guys know a easy way to call upon the pi-blaster.js from afar...
ie. ledHQ.mywebsite.com
Something doesnt want to work...
Situation is currently that the pi shows a slideshow hosted on a website...
It does that through a borderless Chromium.
I'd prefer to use a chromium accesible website :)

**Comment by sarfata** [comment]
You can use nodejs on the raspberry pi to expose a simple webservice to control the LEDs. This goes a bit beyond the scope of this project so I am going to close this ticket.
