### ISSUE TITLE
pi-blaster works but pi-blaster.js does not

### ISSUE THREAD

**Issue by DrCord** [sarfata/pi-blaster.js#9]
I have attempted to use the pi-blaster.js and have tried everything I can think of to debug it...I have followed the examples with no luck.

When I use pi-blaster directly from the command line everything works fine, I can send pwm signals. When I attempt to use pi-blaster.js from within a very simple nodejs application of even at the node console nothing happens.

**Comment by sarfata** [comment]
Can you try again? I think that was fixed thanks to #8.

**Comment by DrCord** [comment]
The changes in #8 plus adding curly braces around the other single line if statements did the trick! thanks for your help. It looks like the GitHub file already has those braces but the version npm downloads does not...Thanks again!

**Comment by sarfata** [comment]
Thanks for pointing this out. I had fixed on github but not republished. I just published v0.1.1. NPM should be ok now.
